CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    ADDITIONAL_NAME VARCHAR(255),
    ADDITIONAL_NAME2 VARCHAR(255),
    ADDITIONAL_NAME3 VARCHAR(255),
    PHONE VARCHAR(255),
    EMAIL VARCHAR(255),
    FAX VARCHAR(255),
    MOBILE VARCHAR(255),
    WEB_SITE VARCHAR(255),
    CITY VARCHAR(255),
    COUNTRY_CODE VARCHAR(255),
    STATE_CODE VARCHAR(255),
    DISTRICT VARCHAR(255),
    STREET VARCHAR(255),
    HOUSE_NUMBER VARCHAR(255),
    STREET_POSTAL_CODE VARCHAR(255),
    ERP_ID VARCHAR(255),
    CREATION_DATE DATE,
    SERIAL_DATA VARCHAR(1048575)
);

CREATE TABLE DUPLICATE (
    DUPLICATE_ID INT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT1_ID BIGINT,
    ACCOUNT2_ID BIGINT,
    SIMILARITY REAL,
    FOREIGN KEY (ACCOUNT1_ID) REFERENCES ACCOUNT,
    FOREIGN KEY (ACCOUNT2_ID) REFERENCES ACCOUNT
);
